apiVersion: v1
kind: Service
metadata:
  name: wordpress
  labels:
    app: wordpress
    owner: maxkoleda
spec:
  type: NodePort
  ports:
    - name: wordpress
      port: 80
      targetPort: 80
      nodePort: 30000
  selector:
    app: wordpress
    tier: frontend
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: wp-pv-claim
  labels:
    app: wordpress
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 20Gi
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: wordpress
  labels:
    app: wordpress
    tier: frontend
    owner: maxkoleda
spec:
  replicas: 1
  selector:
    matchLabels:
      app: wordpress
      tier: frontend
      owner: maxkoleda
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: wordpress
        tier: frontend
        owner: maxkoleda
    spec:
      containers:
      - image: wordpress:6.1.1-apache
        name: wordpress
        env:
        - name: WORDPRESS_DB_HOST
          value: wordpress-mysql
        - name: WORDPRESS_DB_PASSWORD
          valueFrom:
            secretKeyRef:
              name: root-pass
              key: password
        ports:
        - containerPort: 80
          name: wordpress
        volumeMounts:
        - name: wordpress-persistent-storage
          mountPath: /var/www/html
      volumes:
      - name: wordpress-persistent-storage
        persistentVolumeClaim:
          claimName: wp-pv-claim
